version: '3'

services:
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: dbt
    env_file:
      - ./.env
    command: 
      - debug
    restart: unless-stopped
    volumes:
      - ./.dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt:/data/dbt
    # ports:
    #   - "8085:8080"
    environment:
      - TZ=Etc/GMT